const matrizData = {
    "ANL-01": {"titulo": "TEXTO E MANUSCRITOS", "itens": ["Texto hebraico", "Texto aramaico", "Texto grego", "Manuscritos", "Testemunhos textuais", "Variantes textuais", "Crítica textual", "NA28", "BHS / BHQ", "SBLGNT", "Septuaginta"]},
    "ANL-02": {"titulo": "TRADUÇÃO E TEXTO ORIGINAL", "itens": ["Hebraico", "Aramaico", "Grego", "Septuaginta", "Traduções bíblicas", "Comparação de traduções", "Equivalências de tradução", "Diferenças significativas entre traduções"]},
    "ANL-03": {"titulo": "GRAMÁTICA E SINTAXE", "itens": ["Morfologia", "Gramática hebraica", "Gramática aramaica", "Gramática grega", "Sintaxe hebraica", "Sintaxe grega", "Estrutura das frases", "Verbos", "Tempos e aspectos", "Voz", "Modo", "Relações sintáticas", "Conectivos"]},
    "ANL-04": {"titulo": "PALAVRAS E SEMÂNTICA", "itens": ["Palavras-chave", "Lemas", "Formas lexicais", "Campo semântico", "Sentido contextual", "Uso no AT", "Uso no NT", "BDAG", "HALOT", "BDB", "LSJ"]},
    "ANL-05": {"titulo": "SIGNIFICADO TEOLÓGICO", "itens": ["Desenvolvimento dos conceitos", "Vocabulario teológico", "Uso teológico no AT", "Uso teológico no NT", "Relação com a LXX", "NIDNTTE", "NIDOTTE", "TDNT", "TDOT"]},
    "ANL-06": {"titulo": "EXEGESE E CONTEXTO LITERÁRIO", "itens": ["Contexto imediato", "Contexto da passagem", "Estrutura literária", "Argumento do autor", "Intenção comunicativa", "Gênero literário", "Relação entre versículos", "Exegese versículo a versículo", "Comentários bíblicos", "BECNT", "NIGTC", "NICNT", "Pillar", "WBC", "NICOT", "AOTC", "Baker OT"]},
    "ANL-07": {"titulo": "CONTEXTO HISTÓRICO, CULTURAL E RELIGIOSO", "itens": ["Contexto histórico", "Período histórico", "Cultura", "Costumes", "Sociedade", "Instituições", "Religião", "Práticas religiosas", "Grupos religiosos", "Templos", "Sacerdócio", "Festas", "Crenças", "Zondervan Encyclopedia", "IVP Bible Background Commentary", "New Bible Dictionary", "ANET", "Context of Scripture", "Manners and Customs"]},
    "ANL-08": {"titulo": "CONTEXTO GEOGRÁFICO E POLITICO", "itens": ["Localização geográfica", "Cidades", "Regiões", "Territórios", "Fronteiras", "Rotas", "Montanhas", "Rios", "Reinos", "Impérios", "Governantes", "Estruturas políticas", "Guerras", "Conflitos", "Relações de poder", "Arqueologia", "Atlas bíblico", "Zondervan Atlas"]},
    "ANL-09": {"titulo": "RELAÇÃO COM O RESTANTE DA ESCRITURA", "itens": ["Relações AT-NT", "Citações", "Alusões", "Ecos", "Paralelos", "Uso do AT no NT", "LXX e NT", "Relações canônicas", "Desenvolvimento da revelação", "História da redenção", "Beale", "Beale & Carson", "Vos", "Goldsworthy", "Schreiner"]},
    "ANL-10": {"titulo": "HERMENÊUTICA E CONTROLE", "itens": ["Controle interpretativo", "Pressupostos", "Eisegese", "Falácias lexicais", "Descontextualização", "Anacronismo", "Alegorização indevida", "Generalizações", "Descrição x prescrição", "Grant Osborne", "D. A. Carson — Exegetical Fallacies", "Carson & Moo", "Dillard & Longman", "Fee & Stuart"]},
    "ANL-11": {"titulo": "TEOLOGIA E COMPARAÇÃO", "itens": ["Teologia sistemática", "Coerência doutrinária", "Comparação de interpretações", "Concordâncias entre fontes", "Divergências entre fontes", "Argumentos das diferentes interpretações", "Consenso acadêmico", "Posições minoritárias", "Evidências favoráveis e contrárias", "Grudem", "Berkhof", "Frame", "Evangelical Dictionary of Theology", "Comentários bíblicos em comparação"]},
    "ANL-12": {"titulo": "SÍNTESE", "itens": ["Integração das evidências", "Conclusão exegética", "O que o texto afirma", "O que o texto implica", "O que é interpretação", "O que é inferência", "O que é aplicação", "Questões ainda debatidas", "Grau de segurança da conclusão", "Síntese final para geração de conteúdo"]}
};
